added topics in readme for git theory
IshaaqhShaik/JAN_WEB_DEV pull request #22
Opened 2024-01-13 14:45 UTC by Saddamkhanlavani

Added day1/2/3/4 topics for git-theory.

2024-01-17 06:01 UTC, IshaaqhShaik requested changes

2024-01-17 06:01 UTC, IshaaqhShaik commented on README.md
> +        Class - 4:
Please correct the indentation here.

2024-01-17 06:01 UTC, IshaaqhShaik commented on README.md
> +    Class - 3: Git Advanced practical
please correct the indentation here.

2024-01-19 03:04 UTC, Saddamkhanlavani commented on README.md
> +        Class - 4:
corrected the indentation.

2024-01-19 03:04 UTC, Saddamkhanlavani commented on README.md
> +    Class - 3: Git Advanced practical
Completed

2024-01-19 14:59 UTC, Saddamkhanlavani commented on README.md
> +        Class - 4:
Now corrected the indentation.

2024-01-19 15:21 UTC, IshaaqhShaik approved these changes

2024-01-19 15:21 UTC, merged