Module 2 day 1 farooq dev
IshaaqhShaik/JAN_WEB_DEV pull request #24
Opened 2024-01-17 06:39 UTC by farooqgollapallishaik

2024-01-17 11:17 UTC, farooqgollapallishaik commented
Taks.txt is deleted form Task , new Task folder is created in that Farooq_task.html file is added, assignment is added in Farooq_task.html file. 
Cheat Sheet is Modified.

2024-01-17 13:10 UTC, IshaaqhShaik requested changes

2024-01-17 13:10 UTC, IshaaqhShaik commented on Module-2/Day-1/Task/Farooq/Farooq_task.html
> +
create a separate MR for these changes

2024-01-18 09:26 UTC, IshaaqhShaik requested changes
please isolate the cheatsheet and task to respective MR's

2024-01-18 09:27 UTC, IshaaqhShaik requested changes
please isolate the cheatsheet and task to respective MR's

2024-01-19 13:09 UTC, closed without merging