Module 2 day 1 saddam dev
IshaaqhShaik/JAN_WEB_DEV pull request #26
Opened 2024-01-17 09:54 UTC by Saddamkhanlavani

Added html task file and removed saddam_task.txt file under day1 module-2.

2024-01-18 09:21 UTC, IshaaqhShaik commented on Module-2/Day-1/Task/Saddam/saddam_task.html
> +        admin,name;
what does this line do?

2024-01-18 09:21 UTC, IshaaqhShaik requested changes

2024-01-18 09:21 UTC, IshaaqhShaik commented on Module-2/Day-1/Task/Saddam/saddam_task.html
> +    let saddu=[1,2,3];
nothing is being done with this array ?

2024-01-18 18:31 UTC, Saddamkhanlavani commented on Module-2/Day-1/Task/Saddam/saddam_task.html
> +        admin,name;
I had tried to give declare the variables without giving anything before it and it didn't showed anything in the output as previously i had declared the same variables so. and I forgot to remove that after experimenting Now, I had removed it.

2024-01-18 18:36 UTC, Saddamkhanlavani commented on Module-2/Day-1/Task/Saddam/saddam_task.html
> +    let saddu=[1,2,3];
I had made changes to this and added console.log(saddu) as previously after opening live server console, there I had given console.log(saddu) and checked that Iam getting the output as (3) [1, 2, 3]. Now in the code I did the changes.

2024-01-19 15:23 UTC, IshaaqhShaik approved these changes

2024-01-19 15:23 UTC, merged