added cheatsheet for module2-day-4
IshaaqhShaik/JAN_WEB_DEV pull request #47
Opened 2024-01-20 18:14 UTC by Saddamkhanlavani

Added cheat sheet file for module2-day-4.

2024-01-21 13:15 UTC, IshaaqhShaik requested changes

2024-01-21 13:15 UTC, IshaaqhShaik commented on Module-2/Day-4/CheatSheet/Cheatsheet.txt
> +syntax: while (condition) {
indent syntax to next indentation.

2024-01-21 18:23 UTC, Saddamkhanlavani commented on Module-2/Day-4/CheatSheet/Cheatsheet.txt
> +syntax: while (condition) {
corrected indentation for syntax.

2024-01-23 17:34 UTC, IshaaqhShaik approved these changes

2024-01-23 17:34 UTC, merged