cheatSheet is added
IshaaqhShaik/JAN_WEB_DEV pull request #66
Opened 2024-02-02 18:36 UTC by farooqgollapallishaik

Cheat Sheet is added in the Module-3/Day-2/Cheat Sheet folder.

2024-02-07 13:30 UTC, IshaaqhShaik requested changes

2024-02-07 13:30 UTC, IshaaqhShaik commented on Module-3/Day2/CheatSheet/cheatSheet.txt
> +Note: A link does not have to be text. A link can be an image or any other HTML element!
Format the document properly.

2024-02-22 17:11 UTC, abdulhaseebshaik approved these changes

2024-02-22 17:15 UTC, abdulhaseebshaik approved these changes

2024-02-22 17:16 UTC, abdulhaseebshaik approved these changes

2024-02-22 17:20 UTC, IshaaqhShaik approved these changes

2024-02-22 17:20 UTC, merged