Day3 folder is created and respective files are added
IshaaqhShaik/JAN_WEB_DEV pull request #69
Opened 2024-02-04 04:17 UTC by farooqgollapallishaik

Day-3 folder is created and Presentation, Cheat Sheet, Task, folders are added to module-3.

2024-02-04 13:29 UTC, ishaaaqh requested changes

2024-02-04 13:29 UTC, ishaaaqh commented on Module-3/Day3/Task/farooq/Index.html
> +<html lang="en">
Correct naming convention for this file.

2024-02-04 13:29 UTC, ishaaaqh commented on Module-3/Day3/Task/task.img/Allicationform task5.jpeg
Move all this images to Task folder and follow proper naming convention's.

2024-02-04 13:30 UTC, IshaaqhShaik requested changes

2024-02-04 13:30 UTC, IshaaqhShaik commented on Module-3/Day3/Task/task.img/college feedback form-task4.jpeg
Make changes.

2024-02-06 11:33 UTC, IshaaqhShaik approved these changes

2024-02-06 11:34 UTC, IshaaqhShaik approved these changes

2024-02-06 11:34 UTC, merged