added module-3-day-4 task's
IshaaqhShaik/JAN_WEB_DEV pull request #85
Opened 2024-02-19 07:08 UTC by abdulhaseebshaik

Added module-3-day-4 task"s , 
tables task

2024-02-19 11:44 UTC, farooqgollapallishaik commented
Reviewed by farooq

2024-02-20 15:36 UTC, IshaaqhShaik requested changes

2024-02-20 15:36 UTC, IshaaqhShaik commented on Module-3/Day4/Task/Haseeb/task_1.html
> +  <table style="border: 2px solid; margin: 250px;">
instead of applying border manually to every cell use table attribute border.

2024-02-22 17:03 UTC, IshaaqhShaik approved these changes

2024-02-22 17:03 UTC, merged